apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-server
  name: web-server
  namespace: management
spec:
  containers:
  - image: nginx:1.16.1-alpine
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
